
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ticketflex
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345678
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ticketflex?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATA_MONGODB_URI: mongodb+srv://joseluistapiasimanca:Letty_jose1234@ticketflex.ihtijyd.mongodb.net/ticketflex?retryWrites=true&w=majority&appName=ticketflex
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data:
